version: '3.8'

services:
    apigateway:
        container_name: apigateway
        depends_on:
            - api.profissional
            - api.stack
            - api.auth
        ports:
            - "7000:80"

    api.auth:
        container_name: apiauth
        restart: on-failure
        ports:
            - "8001:80"

    api.professional:
        container_name: apiprofessional
        restart: on-failure
        ports:
            - "8002:80"
        depends_on:
            - api.auth

    api.stack:
        container_name: apistack
        restart: on-failure
        ports:
            - "8003:80"
        depends_on:
            - api.auth
            - api.profissional